### PR TITLE
Add Max Pooling layers

### PR DESCRIPTION
**Pull request by CohenAriel**

### CODE REVIEW

**Comment by ducklin5** [comment]
@frjnn, have you had a chance to look at this PR or will this change not work with the rework?

**Comment by frjnn** [comment]
Will look soon and let you know. Don't worry!

**Comment by frjnn** [comment]
I quickly glanced at the code, there should be an easier way by using [as_window](https://github.com/neuronika/neuronika/blob/96b2c92c7373ea2a3109110ca58e1add27cdfed0/neuronika-variable/src/utils.rs#L332). Also, I'm going to merge the `variable-rework` branch into main hopefully pretty soon, would you be able to work on that branch? Thanks a lot. In any case I'll try to provide a sketch of a max pool layer by the end of the week.

**Comment by CohenAriel** [comment]
Hey, sorry it took me time to answer, I didn't have a lot of free time. I think I should close this since you merged the rework. It looks like you still don't have a pooling layer, so I can open another PR.

**Pull request closed without merging**
